server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true

spring:
  devtools:
    restart:
      enabled: true
  jpa:
    show-sql: true
  data:
    rest:
      base-path: /dataApi/