
CREATE TABLE `base_user` (
    `id` BIGINT(20) NOT NULL,
    `name` VARCHAR(64) COLLATE UTF8_BIN DEFAULT NULL,
    `password` VARCHAR(32) COLLATE UTF8_BIN DEFAULT NULL,
    `code` VARCHAR(32) COLLATE UTF8_BIN DEFAULT NULL,
    `phone` VARCHAR(16) COLLATE UTF8_BIN DEFAULT NULL,
    `department` VARCHAR(64) COLLATE UTF8_BIN DEFAULT NULL,
    `create_time` DATETIME DEFAULT NULL,
    `create_user` VARCHAR(64) COLLATE UTF8_BIN DEFAULT NULL,
    `modify_time` DATETIME DEFAULT NULL,
    `modify_user` VARCHAR(64) COLLATE UTF8_BIN DEFAULT NULL,
    PRIMARY KEY (`id`)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE = UTF8_BIN;


CREATE TABLE `file_attach` (
    `id` BIGINT(20) NOT NULL,
    `file_key` VARCHAR(128) COLLATE UTF8_BIN DEFAULT NULL,
    `file_name` VARCHAR(256) COLLATE UTF8_BIN DEFAULT NULL,
    `file_suffix` VARCHAR(64) COLLATE UTF8_BIN DEFAULT NULL,
    PRIMARY KEY (`id`)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE = UTF8_BIN;

CREATE TABLE `login_history` (
    `id` BIGINT(20) NOT NULL,
    `user_id` BIGINT(20) DEFAULT NULL,
    `user_name` VARCHAR(64) COLLATE UTF8_BIN DEFAULT NULL,
    `login_id` VARCHAR(64) COLLATE UTF8_BIN DEFAULT NULL,
    `request_ip` VARCHAR(16) COLLATE UTF8_BIN DEFAULT NULL,
    `login_time` DATETIME DEFAULT NULL,
    `token` VARCHAR(128) COLLATE UTF8_BIN DEFAULT NULL,
    PRIMARY KEY (`id`)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE = UTF8_BIN;


CREATE TABLE `db_data_source` (
	`id` BIGINT (20) NOT NULL,
	`data_source_name` VARCHAR (60) NOT NULL,
	`url` VARCHAR (300) NOT NULL,
	`user_name` VARCHAR (30) NOT NULL,
	`driver_class_name` VARCHAR (60) NOT NULL,
	`password` VARCHAR (128) NOT NULL,
	`create_time` DATETIME DEFAULT NULL,
	`create_user` VARCHAR (64) COLLATE UTF8_BIN DEFAULT NULL,
	`modify_time` DATETIME DEFAULT NULL,
	`modify_user` VARCHAR (64) COLLATE UTF8_BIN DEFAULT NULL,
	PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE = UTF8_BIN;